### ISSUE TITLE
Function app blade throws errors when opening

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1149]
_From @rndthoughts on January 24, 2017 14:38_

My existing Function app started throwing errors which appear in the browser as a red box indicating "We are unable to reach your function app (Internal Server Error). Please try again later".  In the browser console, the following can be seen:

```
HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)GET - https://uk-test-uefunctions.scm.azurewebsites.net/api/functions/admin/masterkey
```

```
AI: USRACT_StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:{\_body\:\{\\\Message\\\:\\\An error has occurred.\\\,\\\ExceptionMessage\\\:\\\The payload was invalid.\\\,\\\ExceptionType\\\:\\\System.Security.Cryptography.CryptographicException\\\,\\\StackTrace\\\:\\\   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)\\\\r\\\\n   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)\\\\r\\\\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)\\\\r\\\\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)\\\\r\\\\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingB}"
ai.0.js (1,6251)
```

I have tried signing out and back in with and without browser closing, multiple browsers, clearing the cache, none of which resolve the issue.  I also tried deleting my function app and creating a brand new one - same result.

_Copied from original issue: projectkudu/AzureFunctionsPortal#888_

**Comment by lindydonna** [comment]
@fabiocav Could you investigate?  Seems related to keys.

**Comment by rndthoughts** [comment]
Update on this - my scenario is that I deleted the Function app and recreated it with the same name and storage account not realising that the associated folders in the azure-webjobs-hosts remains after deletion.  Therefore I'm guessing the new functions app was trying to use the data from the same folder created by the previous one.

I'm guessing the solution to this is for Azure to remove the storage account files on function app deletion so that it clears up after itself?  Or at least give the user the option to do so when they delete?

Once i'd removed the associated storage files and recreated the function app, all was well.

**Comment by rndthoughts** [comment]
Futher update :)

All WAS well, and then I attempted to deploy my changes again (I'm using VSO Build + Release with a WebDeploy step).  I have two functions apps - test and live.  I deployed to test with no problems but when I deployed the same code to live deployment the same errors came back about missing keys and the default key entries are missing under each function's "Manage" tab although the admin ones are still present. There's a whole bunch of CORS errors as well.

![image](https://cloud.githubusercontent.com/assets/4190823/22331164/d9a75028-e3c1-11e6-9a44-8da54fac6a4d.png)

As i can't see this "admin" folder in which the keys live, could webdeploy remove them?  It looks like it isn't physically present in storage so I assume it's some sort of virtual folder.

**Comment by lindydonna** [comment]
@rndthoughts Are you using the new Functions project type to deploy from VSO?  Also, could you provide the directory structure that you are deploying?

**Comment by christopheranderson** [comment]
@lindydonna - we could solve this by adding some random characters to the name we use for the file content store - this would be added to the arm template you use from the portal "New Function App"

@fabiocav - suggests we could also let you choose the encryption key as a feature. This would allow us to roll the encryption key that is used to protect the secrets. This already works, we just need to expose this via UI/API/etc.

I suggest both! I think this may be best solved by portal updates - no host fixes are needed.

**Comment by lindydonna** [comment]
@christopheranderson Agree. The first can be done in only Ibiza as a tactical fix.

**Comment by lindydonna** [comment]
@rndthoughts We're going to fix this by adding random characters to the content share path. See https://github.com/projectkudu/AzureFunctionsPortal/issues/893.

I recommend you do the following to fix your apps:
- Delete the function app
- Delete the file shares where your code lives (see screenshot below)
- Redeploy

If you are deploying with an ARM template, you can use a template parameter to change the value of `WEBSITE_CONTENTSHARE`.

![image](https://cloud.githubusercontent.com/assets/4260261/22357744/11fb6b8a-e3ef-11e6-9dae-a309763fa24a.png)

If that doesn't fix your issue, please post on the [forums](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions) or Stack Overflow and we'll see how we can get you to a working state.

**Comment by rndthoughts** [comment]
@lindydonna I agree that the random characters addition would fix issues of the recreation of the functions app with the same name but I also got the same key issues when i created a brand new functions app in the same storage account with a different name.  Thanks for clarifying about the File Shares though, i didn't realise that was where the files were stored!

**Comment by lindydonna** [comment]
Reopening issue since @rndthoughts is still seeing an error with a new Function App (with a new name) using the same storage account.

@rndthoughts Could you please share the exact repro steps?

**Comment by rndthoughts** [comment]
The steps I took were:

# Create Functions App with a given name and storage account.
# Create a sample function (I used the C# Timer one)
# Go to app service settings and delete the application in Azure.
# Create a new Functions App with a different name and the same storage account.
# Open the Function app in the Azure portal - the keys errors appear.

**Comment by lindydonna** [comment]
@fabiocav Any ideas?

**Comment by lindydonna** [comment]
The issue should be resolved even when using the same Function App name, see https://github.com/projectkudu/AzureFunctionsPortal/issues/899

**Comment by fabiocav** [comment]
@rndthoughts we're unable to repro this with the scenario you've described. Is this still occurring? Please let us know and I'll reopen for investigation if it is.

**Comment by rndthoughts** [comment]
I haven't run across this again.  I suspect it was all to do with the speed I was creating, deleting and recreating the Functions app.  Thanks for investigating.
