### ISSUE TITLE
Support .NET Standard 2.0 class libraries

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1792]
Now that .NET Standard 2.0 is RTM, we should include the facades that enable support on full framework. This is especially important once we port to .NET Core.

**Comment by davidebbo** [comment]
This came up on https://social.msdn.microsoft.com/Forums/azure/en-US/3f611936-256a-4003-ab11-3f0d0fa66233/object-not-set-to-instance-of-an-object?forum=AzureFunctions

**Comment by solvingj** [comment]
The current impact seems to be that you actually cannot have any .NET Standard 2.0 library projects referenced in an Azure Function Project (which are framework v4.6.1) at this time. The act of simply referencing an empty Netstandard2.0 project causes a runtime failure of the functions.  I don't know what the scope of scenarios are where this will/won't throw an exception.

**Comment by davidebbo** [comment]
Yes, this is pretty bad and leads to very puzzling situations. We'll need to address it.

**Comment by solvingj** [comment]
Maybe just start by warning people the exciting new update of Netstandard 2.0 is currently strictly incompatible with azure functions since they won't get Nuget or Compiler warnings and will have to find out via obscure debugging like I did.

**Comment by solvingj** [comment]
David or Lindy, can you confirm that this would be an effective workaround for the HttpClient issue?
https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/

**Comment by fabiocav** [comment]
@solvingj the above will not be effective. There would also be other issues you'd run into. We'll have an update, with hopefully a better ETA on the proper support, after this week's triage process (which is happening tomorrow).

**Comment by solvingj** [comment]
That's an outstanding update already, thank you so much for the feedback.  Will look forward to tomorrow.

**Comment by solvingj** [comment]
@fabiocav any updates?

**Comment by fabiocav** [comment]
Sorry, due to some conflicts this week, the triage process was pushed to tomorrow. We'll have an update then.

**Comment by gongdo** [comment]
I'm not sure is this a same problem, but I'm piling up my problem related with .NET Standard 2.0.
It seems that some .NET Standard 2.0 libraries break Web Jobs process somehow.
https://github.com/gongdo/ReproduceFunctionAppFailure

**Comment by fabiocav** [comment]
@gongdo I just want to confirm, this happens when loading the `LoggingLibraryDummyCore` project/assemblies, correct? When referencing .NET Standard 2.0 assemblies, you'll run into those kinds of problems (they manifest differently depending on the scenario). We'll have that addressed this sprint and will update this issue when that is done.

**Comment by gongdo** [comment]
@fabiocav You can break down the problem to reproduce it like this:
1. When LoggingFunctionApp have package reference to `Microsoft.Extensions.Logging.Abstraction`
2. When LoggingFunctionApp have project reference to `LoggingLibraryDummyCore` which have package reference to `Microsoft.Extensions.Logging.Abstraction`

But To reference .NET 461 project works fine.

**Comment by dasMulli** [comment]
Ad binding redirects: When a project targets .net framework and does not have `<OutputType>Library</…>`, automatic binding redirects generation is disabled in msbuild and needs to be enabled manually (the second property is important):

```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```xml

**Comment by dasMulli** [comment]
Didn't work out that well for me 😬  thanks @solvingj for reminding me to keep my mouth shut until I actually confirm it works. Been looking at similar issues at the moment (https://github.com/Microsoft/msbuild/issues/2481)

**Comment by solvingj** [comment]
I hope it didn't come off negatively, I didn't mean it that way, all suggestions should be welcome! I was actually hoping because I wanted something to work.  TBH, I'm glad to see you're looking tbh. I feel like you might find a workaround while we wait :)

**Comment by solvingj** [comment]
FYI i just downloaded and installed an update to azure functions and webjobs tools.  i still get the following at runtime when hitting my function (during local debug): 

```
mscorlib: Exception while executing function: AgentsPost. API.Routing: Method not found: 'System.Net.Http.HttpResponseMessage System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, System.String)'.
```
I'm not even positive that this error was one of the many targeted to be addressed in this sprint, but it's the error @davidebbo associated back to this ticket.  Perhaps someone can confirm that this error is related to this ticket.

**Comment by fabiocav** [comment]
@solvingj this will be addressed in this sprint, with the same set of changes.

**Comment by fabiocav** [comment]
Addressed by #1863

**Comment by solvingj** [comment]
Any ETA on release and availability?

**Comment by davidebbo** [comment]
Hopefully today in one region, and then propagating over the next few days. If you have cycles to help us verify in the initial region by deploying a test site, that would help us validate.

**Comment by solvingj** [comment]
Sure, what's the region.  FYI, I still have the bug where my local debug session crashes.  I thought that would be fixed before it was live on Azure.

**Comment by davidebbo** [comment]
I will likely be 'West US 2' (different from 'West US'), but it's not there yet. We'll let you know.

We'll need to release a new version of the client tools as well.

**Comment by solvingj** [comment]
Setting up to deploy there now to validate the original failure condition beforehand.

**Comment by davidebbo** [comment]
Awesome, thanks!

**Comment by solvingj** [comment]
Upon deployment...
```
Wed 09/13   An unknown error has occurred. Check the diagnostic log for details.
```
Can't seem to find the deployment diagnostic log in kudu console.

**Comment by davidebbo** [comment]
Odd, can you share the test app name?

**Comment by solvingj** [comment]
Invited you to the app on github. Did you want the app name in azure?

**Comment by davidebbo** [comment]
Yes, the app name in Azure. There is a way to give it [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly), though in this case since you created a temporary test app, I'm guessing the name has no real value.

**Comment by solvingj** [comment]
appany-testapp-01

**Comment by davidebbo** [comment]
And to be clear, is that the app where you saw the issue, or the indirect app used to give me the other app's name?

**Comment by solvingj** [comment]
That's just the test app i created for this exercise.  It's got the real code from my function app behind it.

**Comment by solvingj** [comment]
Also, important point... Kudu was able to pull in the latest commit to the original function-app deployed in Central US.

**Comment by davidebbo** [comment]
Ok, I see that's the app where you deployed. Take a look at D:\home\LogFiles\kudu\trace in Kudu console, specifically the file that has Background_POST in its name. Seems something caused it to suddenly die.

I'm not sure what happened there, but it is most likely unrelated to this issue. Can you try just pushing again?

**Comment by solvingj** [comment]
Sure, just did "sync" again on the test app (project uses Github deploy). 
As for the deployment in central region, looks like we're currently in good shape, reproducing the expected error: 

```
"message": "Exception while executing function: ReposGet -> Method not found: 'System.Net.Http.HttpResponseMessage System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, System.String)'."
```

**Comment by davidebbo** [comment]
FYI, the deployment is now looking more like it'll start tomorrow and not today.

**Comment by davidebbo** [comment]
Forgot to  follow up yesterday, but the change is now live in West US 2 if you want to give it a try!

**Comment by dieterhowest** [comment]
Is there a SDK update because i have a Azure Function project that references a .NET Standard 2.0 library but i get the following message (see screenshot attached)

![capture](https://user-images.githubusercontent.com/1374511/30509931-5d4de8e6-9abb-11e7-8129-89c24eea821d.PNG)

**Comment by dersia** [comment]
@dieterhowest your issue has nothing todo with netstandard2.0 support. Your issue basically comes from using a higher version of System.Runtime than is available on the host. You cloud try referencing version 4.2.0 in your project.json or change your assembly to use 4.1.2

**Comment by davidebbo** [comment]
Note that the Azure App Service deploy I mentioned above is now complete.

**Comment by solvingj** [comment]
All regions or just West US 2?

**Comment by davidebbo** [comment]
@solvingj All regions as of this morning. West US 2 was 4 days ago.

**Comment by joelhulen** [comment]
@davidebbo Great news! Have you guys released a new version of the SDK to address this issue while testing locally, yet?

**Comment by davidebbo** [comment]
The npm core tools are out, but the VS extension is due soon. You can work around using https://stackoverflow.com/questions/46269046/azure-function-structure/46289792#46289792

**Comment by solvingj** [comment]
Can you clarify if it's weeks or months?

**Comment by davidebbo** [comment]
@solvingj for the VS extension, days. Should be this week.

**Comment by dersia** [comment]
I just tried to add a .netstandard 2.0 package to my function. Seems not to work, or did I miss anything?

```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "My.NetStandard20.Shared": "1.0.0-alpha-128",
        "Microsoft.Extensions.DependencyInjection": "2.0.0",
        "Microsoft.Extensions.Configuration": "2.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "2.0.0",
        "System.Diagnostics.TraceSource": "4.0.0.0",
        "System.Reflection.TypeExtensions": "4.0.0.0",
        "Microsoft.Extensions.Logging": "2.0.0",
        "Microsoft.Extensions.Logging.Console": "2.0.0"
      }
    }
   }
}
```

here is the log: 

```
2017-09-25T17:38:30.061 Errors in D:\home\site\wwwroot\myfunction\project.json
2017-09-25T17:38:30.061 Package My.NetStandard20.Shared 1.0.0-alpha-128 is not compatible with net46 (.NETFramework,Version=v4.6). Package My.NetStandard20.Shared 1.0.0-alpha-128 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 Package Microsoft.Extensions.DependencyInjection 2.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Extensions.DependencyInjection 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 Package Microsoft.Extensions.Configuration 2.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Extensions.Configuration 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 Package Microsoft.Extensions.Logging 2.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Extensions.Logging 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 Package Microsoft.Extensions.Logging.Console 2.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Extensions.Logging.Console 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-09-25T17:38:30.061 One or more packages are incompatible with .NETFramework,Version=v4.6.
```

**Comment by fabiocav** [comment]
@dersia that is a known issue. We'll be addressing that as part of the move from `project.json` to the MSBuild format. You can track this [here](https://github.com/Azure/azure-webjobs-sdk-script/issues/1928).

We're maintaining a list of known issues [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Azure-Functions-runtime-2.0-known-issues).

**Comment by dersia** [comment]
@fabiocav ok, great is there any workaround?

**Comment by fabiocav** [comment]
No great workarounds at this point, but this shouldn't take long.

**Comment by bluechipalex** [comment]
we're running into the same thing on our team - thanks in advance for the fix!

**Comment by dersia** [comment]
@fabiocav just to make sure, so loading netstandard2.0 from nuget is a problem, but uploading those to let's say the ```bin``` and then referencing with ```#r "../bin/mypackage.dll"``` should work?

**Comment by fabiocav** [comment]
@dersia yes, that should work as expected.

**Comment by dersia** [comment]
unfortunately it doesn't:  
```
Function ($readmodeljob-service) Error: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```
![image](https://user-images.githubusercontent.com/1537958/30994433-c4fa44c4-a468-11e7-9b65-e87741ad258a.png)

**Comment by fabiocav** [comment]
This could also be caused by a failed dependency. If you have a simple repro and could open a separate issue with the details so it's tracked, I'll take a look at this.

**Comment by dersia** [comment]
ok, will create a repro

**Comment by dersia** [comment]
@fabiocav I created a simple repro: https://github.com/dersia/afnetstandard2.0test

Running this manual triggered function from the portal logs the following:
```
2017-09-28T23:43:57.937 Function started (Id=00bb0302-3413-4de1-960b-54db655144c4)
2017-09-28T23:43:58.234 Exception while executing function: Functions.ManualTriggerCSharp1. mscorlib: Exception has been thrown by the target of an invocation. f-ManualTriggerCSharp1__-1357806294: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
2017-09-28T23:43:58.283 Function completed (Failure, Id=00bb0302-3413-4de1-960b-54db655144c4, Duration=351ms)
```

**Comment by jmevel** [comment]
I think this is still not fixed.

I have an Azure Functions project referencing a .NET Standard 2.0 project. My .NET Standard project references Microsoft.Extensions.Logging.Abstractions 2.1.1.

When I debug the project in Visual Studio I get the error

> Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

Notice the version number 2.0.1.0 different from version 2.1.1 I'm referencing in the .NET Standard Nuget package
I have no idea why it is looking for this version.

I thought I was again in one of these binding redirects issues. So I changed the target Framework version of my Azure Functions project to 4.7.2 which is supposed to be the version fixing all the binding redirects issue when referencing a .NET Standard project.

But this didn't solve the problem. So I also tried to install the Microsoft.Extensions.Logging.Abstractions Nuget package version 2.0.1 in a separate .NET Framework Console Application.

I copied the Microsoft.Extensions.Logging.Abstractions.dll (I verified with ildasm.exe it's version 2.0.1) to the bin folder of my Azure Functions project but still the same error.

So I'm confused on why this issue has been closed and supposed to be fixed. On my side it's clearly not fixed.
Anyone has a workaround?

Thank you

**Comment by jmevel** [comment]
I think this is still not fixed.

I have an Azure Functions project referencing a .NET Standard 2.0 project. My .NET Standard project references Microsoft.Extensions.Logging.Abstractions 2.1.1.

When I debug the project in Visual Studio I get the error

> Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

Notice the version number 2.0.1.0 different from version 2.1.1 I'm referencing in the .NET Standard Nuget package
I have no idea why it is looking for this version, I've zero result for the string `2.0.1` in my entire solution

I thought I was again in one of these binding redirects issues. So I changed the target Framework version of my Azure Functions project to 4.7.2 which is supposed to be the version fixing all the binding redirects issue when referencing a .NET Standard project.

But this didn't solve the problem. So I also tried to install the Microsoft.Extensions.Logging.Abstractions Nuget package version 2.0.1 in a separate .NET Framework Console Application.

I copied the Microsoft.Extensions.Logging.Abstractions.dll (I verified with ildasm.exe it's version 2.0.1) to the bin folder of my Azure Functions project but still the same error.

And this is actually not the only DLL causing problems. My Azure Functions project also references another .NET Standard project which has a dependency to System.Data.SqlClient and I get the same issue.

So I'm confused on why this issue has been closed and supposed to be fixed. On my side it's clearly not fixed.
Anyone has a workaround?

Thank you
